# Generated by Django 5.0.6 on 2026-06-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField()),
                ('licencia_numero', models.CharField(blank=True, max_length=50)),
                ('licencia_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('licencia', 'De licencia'), ('inactivo', 'Inactivo')], db_index=True, default='activo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='choferes/')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'chofer',
                'verbose_name_plural': 'choferes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
