# Generated by Django 5.0.6 on 2026-06-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(db_index=True, max_length=20, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveSmallIntegerField()),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_chasis', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En mantenimiento'), ('inactivo', 'Inactivo')], db_index=True, default='activo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['patente'],
            },
        ),
    ]
