# Generated by Django 5.0.6 on 2026-06-14 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('viajes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('peajes', 'Peajes'), ('viaticos', 'Viáticos'), ('reparaciones', 'Reparaciones'), ('neumaticos', 'Neumáticos'), ('mantenimiento', 'Mantenimiento'), ('seguros', 'Seguros'), ('impuestos', 'Impuestos'), ('otros', 'Otros')], db_index=True, max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/comprobantes/')),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Para gastos sin viaje asociado (seguros, impuestos, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='vehiculos.vehiculo')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['categoria', 'fecha'], name='ingresos_ga_categor_bdd13b_idx'), models.Index(fields=['viaje', 'categoria'], name='ingresos_ga_viaje_i_f8013a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque'), ('credito', 'Crédito')], max_length=20)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='ingresos/comprobantes/')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='clientes.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'ingreso',
                'verbose_name_plural': 'ingresos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='ingresos_in_fecha_ff9bc2_idx'), models.Index(fields=['cliente', 'fecha'], name='ingresos_in_cliente_b2c589_idx')],
            },
        ),
    ]
