# Generated by Django 5.0.6 on 2026-06-14 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_combustible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'carga de combustible',
                'verbose_name_plural': 'cargas de combustible',
                'ordering': ['-fecha'],
            },
        ),
    ]
