# Generated by Django 5.0.6 on 2026-06-14 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], db_index=True, max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField(db_index=True)),
                ('kilometraje', models.PositiveIntegerField()),
                ('proveedor', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('numero_orden', models.CharField(blank=True, max_length=100)),
                ('proximo_mantenimiento_fecha', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento_km', models.PositiveIntegerField(blank=True, null=True)),
                ('alerta_enviada', models.BooleanField(default=False)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='mantenimiento/')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'mantenimiento',
                'verbose_name_plural': 'mantenimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['vehiculo', 'fecha'], name='mantenimien_vehicul_f7e7af_idx'), models.Index(fields=['proximo_mantenimiento_fecha'], name='mantenimien_proximo_80f62e_idx')],
            },
        ),
    ]
