# Generated by Django 5.0.6 on 2026-06-14 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choferes', '0001_initial'),
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_viaje', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('fecha_salida', models.DateField(db_index=True)),
                ('fecha_regreso', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('km_iniciales', models.PositiveIntegerField()),
                ('km_finales', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='programado', max_length=20)),
                ('carga_descripcion', models.CharField(blank=True, max_length=500)),
                ('carga_peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='choferes.chofer')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='clientes.cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_creados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
                'ordering': ['-fecha_salida'],
                'indexes': [models.Index(fields=['estado', 'fecha_salida'], name='viajes_viaj_estado_66bdc7_idx'), models.Index(fields=['vehiculo', 'estado'], name='viajes_viaj_vehicul_99a3e4_idx'), models.Index(fields=['chofer', 'fecha_salida'], name='viajes_viaj_chofer__662e93_idx')],
            },
        ),
    ]
